commons:
    sitename: "Kiribi Ususama"
    description: "gulpを使用した小・中規模Webサイト制作用のボイラープレート"
    year: 2019
    author: "アルム＝バンド"
    url: "https://localhost:3000/"
param:
    news:
        indexcount: 3
        newscount: 6
    ogp:
        ogpimage: "img/eyecatch.jpg"
        twitteraccount: "Bredtn_1et"
        newsthumbnail: "img/thumbnails/"
    analytics:
    searchconsole:
    articlesns:
        twitter: true
        facebook: true
        hatena: true
        line: true
        pocket: true
        feedly: true