commons:
    sitename: "Kiribi Ususama"
    description: "gulpを使用した小・中規模Webサイト制作用のボイラープレート"
    year: 2018
    author: "アルム＝バンド"
    url: "http://localhost:3000/"
param:
    news:
        indexcount: 3
        newscount: 6
    ogp:
        ogpimage: "img/eyecatch.jpg"
        twitteraccount: "Bredtn_1et"
        newsthumbnail: "img/thumbnails/"
    analytics: ""
    articlesns:
        twitter: true
        facebook: true
        googleplus: false
        line: true
        pocket: true
        feedly: true