commons:
    sitename: "Kiribi Ususama"
    description: "gulpを使用した小・中規模Webサイト制作用のボイラープレート"
    year: 2018
    author: "アルム＝バンド"
    url: "http://localhost:3000/"
    ogpimage: "img/eyecatch.jpg"
    twitteraccount: "Bredtn_1et"
    newsthumbnail: "img/thumbnails/"
param:
    indexcount: 3
    newscount: 6